/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IEditionFactoryInterface extends ethers.utils.Interface {
  functions: {
    "logic()": FunctionFragment;
    "parameters()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "logic", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "parameters",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "logic", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "parameters", data: BytesLike): Result;

  events: {};
}

export class IEditionFactory extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IEditionFactoryInterface;

  functions: {
    logic(overrides?: Overrides): Promise<ContractTransaction>;

    "logic()"(overrides?: Overrides): Promise<ContractTransaction>;

    parameters(overrides?: Overrides): Promise<ContractTransaction>;

    "parameters()"(overrides?: Overrides): Promise<ContractTransaction>;
  };

  logic(overrides?: Overrides): Promise<ContractTransaction>;

  "logic()"(overrides?: Overrides): Promise<ContractTransaction>;

  parameters(overrides?: Overrides): Promise<ContractTransaction>;

  "parameters()"(overrides?: Overrides): Promise<ContractTransaction>;

  callStatic: {
    logic(overrides?: CallOverrides): Promise<string>;

    "logic()"(overrides?: CallOverrides): Promise<string>;

    parameters(
      overrides?: CallOverrides
    ): Promise<[string, string] & { name: string; symbol: string }>;

    "parameters()"(
      overrides?: CallOverrides
    ): Promise<[string, string] & { name: string; symbol: string }>;
  };

  filters: {};

  estimateGas: {
    logic(overrides?: Overrides): Promise<BigNumber>;

    "logic()"(overrides?: Overrides): Promise<BigNumber>;

    parameters(overrides?: Overrides): Promise<BigNumber>;

    "parameters()"(overrides?: Overrides): Promise<BigNumber>;
  };

  populateTransaction: {
    logic(overrides?: Overrides): Promise<PopulatedTransaction>;

    "logic()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    parameters(overrides?: Overrides): Promise<PopulatedTransaction>;

    "parameters()"(overrides?: Overrides): Promise<PopulatedTransaction>;
  };
}
