/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { ICrowdfundFactory } from "../ICrowdfundFactory";

export class ICrowdfundFactory__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICrowdfundFactory {
    return new Contract(address, _abi, signerOrProvider) as ICrowdfundFactory;
  }
}

const _abi = [
  {
    inputs: [],
    name: "logic",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "mediaAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "parameters",
    outputs: [
      {
        internalType: "address payable",
        name: "operator",
        type: "address",
      },
      {
        internalType: "address payable",
        name: "fundingRecipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "fundingCap",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "operatorPercent",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "name",
        type: "string",
      },
      {
        internalType: "string",
        name: "symbol",
        type: "string",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];
