/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IEditionFactory } from "../IEditionFactory";

export class IEditionFactory__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IEditionFactory {
    return new Contract(address, _abi, signerOrProvider) as IEditionFactory;
  }
}

const _abi = [
  {
    inputs: [],
    name: "logic",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "parameters",
    outputs: [
      {
        internalType: "string",
        name: "name",
        type: "string",
      },
      {
        internalType: "string",
        name: "symbol",
        type: "string",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];
